feeds:
  - name: Feed1
    url: "https://audio.broadcastify.com/32602.mp3"
    provider: broadcastify

write_path: ./output

providers:
  broadcastify:
    user: "${BROADCASTIFY_USER}"
    password: "${BROADCASTIFY_PASSWORD}"

models:
  whisper:
    # ["tiny", "base", "small", "medium", "large"]
    # append .en to use english-only
    size: "medium.en"
