version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.4
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.4#configuration for more options
            PBF_URL: https://download.geofabrik.de/north-america/us-midwest-latest.osm.pbf 
            REPLICATION_URL: https://download.geofabrik.de/north-america/us-updates/
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
            - nominatim-data:/nominatim/flatnode
        shm_size: 1gb

volumes:
    nominatim-data: